%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 512
image_height: 384
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 272.8701
   fy: 273.231243697
   cx: 258.394922795
   cy: 199.844170744 
